# Generated by Django 5.1.1 on 2024-09-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_activity', models.DateField()),
                ('material_extracted', models.CharField(max_length=100)),
                ('quantity_extracted', models.PositiveIntegerField()),
                ('energy_consumption', models.PositiveIntegerField()),
                ('fuel_consumption', models.PositiveIntegerField()),
                ('operational_hours', models.DurationField()),
                ('downtime_duration', models.DurationField()),
                ('production_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trucks_loaded', models.PositiveIntegerField()),
                ('distance_mined', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='graphs/')),
                ('mining_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='coal.miningactivity')),
            ],
        ),
    ]
