# Generated by Django 5.1.1 on 2024-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miningactivity',
            name='energy_grid_mix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miningactivity',
            name='explosives_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miningactivity',
            name='fuel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='miningactivity',
            name='total_explosives_used',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='miningactivity',
            name='distance_mined',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='miningactivity',
            name='downtime_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='miningactivity',
            name='operational_hours',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='miningactivity',
            name='production_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='miningactivity',
            name='trucks_loaded',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
